---
# - hosts: all
# - name: Include dynamic variables 
  # import_playbook: ../static-assignments/common.yml 
  # include: ../dynamic-assignments/env-vars.yml
  # tags:
  #   - always

# - hosts: webservers
# - name: Webserver assignment
#   import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: db
# - name: database mysql configuration
#   import_playbook: ../static-assignments/uat-webservers.yml

# - name: nginx
#   import_playbook: ../static-assignments/loadbalancers.yml
 
# - name: artifactory
#   import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: todo
# - name: app deployment
#   import_playbook: ../static-assignments/deployment.yml

- hosts: sonarqube
- name: sonarqube deployment
  import_playbook: ../static-assignments/sonarqube.yml


