---
# handlers file for distribution
- name: Restart artifactory
  become: true
  ansible.builtin.systemd:
    name: "{{ artifactory_daemon }}"
    state: restarted
    daemon_reload: true
  when:
    - artifactory_start_service | bool 

- name: Stop artifactory
  become: true
  ansible.builtin.systemd:
    name: "{{ artifactory_daemon }}"
    state: stopped
